// Generated by CoffeeScript 1.4.0
var init, jQ, rnd, update;

jQ = jQuery;

rnd = function(x, n) {
  var a;
  a = (Math.round(x * Math.pow(10, n))) / Math.pow(10, n);
  return a;
};

init = function() {
  (jQ('#feet_x,#feet_y')).change(function() {
    (jQ('#acres')).val(rnd(parseFloat((jQ('#feet_x')).val() * parseFloat((jQ('#feet_y')).val() / 43560)), 4));
    (jQ('#sqmiles')).val(rnd(parseFloat((jQ('#feet_x')).val() * parseFloat((jQ('#feet_y')).val() / 27878400)), 4));
    return update();
  });
  (jQ('#acres')).change(function() {
    (jQ('#feet_x,#feet_y')).val(rnd(Math.sqrt(parseFloat((jQ('#acres')).val() * 43560)), 1));
    (jQ('#sqmiles')).val(rnd(parseFloat((jQ('#acres')).val() / 640), 4));
    return update();
  });
  (jQ('#sqmiles')).change(function() {
    (jQ('#feet_x,#feet_y')).val(rnd(Math.sqrt(parseFloat((jQ('#sqmiles')).val() * 27878400)), 1));
    (jQ('#acres')).val(rnd(parseFloat((jQ('#sqmiles')).val() * 640), 1));
    return update();
  });
  (jQ('#rain_in')).change(function() {
    return update();
  });
  (jQ('#update')).click(function() {
    return (jQ('#answer')).fadeOut().fadeIn();
  });
  return (jQ('#feet_x')).change();
};

update = function() {
  var baths, cuft, cum, gal, inch, kg, pint, pnds, sqft, tab, text, tonnes, tons, x, _i, _len, _ref, _ref1, _results;
  tab = jQ('#answer');
  tab.empty();
  sqft = parseFloat((jQ('#feet_x')).val() * parseFloat((jQ('#feet_y')).val()));
  inch = parseFloat((jQ('#rain_in')).val());
  cuft = sqft * inch / 12;
  cum = cuft / 35.3147;
  gal = cuft * 7.48052;
  pnds = 8.345404 * gal;
  tons = pnds / 2000;
  kg = cum * 1000;
  tonnes = kg / 1000;
  baths = gal / 35;
  pint = 8 * gal;
  _ref = [['cubic feet', cuft], ['gallons', gal], ['pints', pint], ['pounds', pnds], ['baths (35 gallon)', baths], ['tons', tons], ['cubic meters', cum], ['kg', kg], ['metric tons', tonnes]];
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    _ref1 = _ref[_i], text = _ref1[0], x = _ref1[1];
    x = rnd(x, 2);
    _results.push(tab.append("<tr><td>" + text + "</td><td>" + x + "</td></tr>"));
  }
  return _results;
};

jQ(init);
